CREATE DATABASE DataAnalytics;


USE DataAnalytics;
GO

SELECT TOP 10 *
FROM customer_data;


/* What is total revenue generated by male and female */

select gender,SUM(purchase_amount) as revenue_by_gender from customer_data
group by gender

/* which customers used a discount but still spent more than the averge purchase amount*/

select customer_id ,discount_applied,purchase_amount from customer_data
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer_data)

/*3 which are the top 5 products with highest average review rating */

select top 5 item_purchased,Round(avg(review_rating),1) as av_rating from customer_data
group by item_purchased
order by av_rating desc

/* Compare the average purchase amount between standards and express in shippping*/

select shipping_type,round(avg(purchase_amount),2) as avg_amount from customer_data
where shipping_type in ('Standard','Express')
group by shipping_type

/* Do subscribers customers spend more?compare avg spend and total revenue between subscriber and non-sunbscribers*/

select count(customer_id) as total_customers,subscription_status,sum(purchase_amount) as total,round(avg(purchase_amount),3) as avg_amount from customer_data
group by subscription_status


/*  Which 5 products  have the highest  percentage of purchases with the discount*/

select top 5 item_purchased,
round(100*sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*),2) as discount_percentage
from customer_data
group by item_purchased
order by discount_percentage  desc

/* Segment customers into New, Returning and Loyal based on their total number of previous purchases and show the count of each segment */

select customer_segments,count(customer_segments) as no_of_customers from (
	select previous_purchases,frequcny_purchase_days,
	case when previous_purchases = 5 Then 'New Customers'
		when previous_purchases between 1 and 10 Then 'Returning'
		else 'Loyal'
		end as customer_segments
	from customer_data
)t
group by customer_segments
order by no_of_customers desc

/* what are the top 3 products from within each category */
with item_counts as(
select  item_purchased,
count(customer_id)  as total_orders,
category ,
ROW_NUMBER() over(partition by category order by count(customer_id) desc) as rnk_items
from customer_data
group by category,item_purchased)

select rnk_items,category,item_purchased,total_orders from item_counts
where rnk_items <= 3


/*  Customers who are repeat buyer (more than 5 purchases) also likely to subscribe */

select 
count(customer_id) as repeat_buyer,
subscription_status
from customer_data
where previous_purchases > 5
group by subscription_status

/* what is the revenue contribution of each age group */

select age_group,sum(purchase_amount) as contribute_revenu_by_age_group from customer_data
group by age_group
order by contribute_revenu_by_age_group desc
